language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=isort }

install:
  - pip install tox coveralls
  - pip install -r requirements.txt

before_script:
  - cp .env.json.example .env.json

script:
  - tox

after_success:
  - coveralls
