language: python

matrix:
  include:
    - { python: 3.4, env: TOXENV=py34 }
    - { python: 3.5, env: TOXENV=py35 }
    - { python: 3.6, env: TOXENV=py36 }
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=isort }

install:
  - pip install tox coveralls
  - pip install -r requirements.txt

before_script:
  - cp .env.json.example .env.json

script:
  - tox -e $TOXENV

after_success:
  - coveralls
