language: python
dist: xenial
sudo: required
matrix:
  include:
    - { python: 3.4, env: TOXENV=py34 }
    - { python: 3.5, env: TOXENV=py35 }
    - { python: 3.6, env: TOXENV=py36 }
    - { python: 3.7, env: TOXENV=py37 }
    - { python: 3.8-dev, env: TOXENV=py38-dev }
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=isort }
  allow_failures:
    - { python: 3.8-dev, env: TOXENV=py38-dev }
install:
  - pip3 install tox coveralls
  - pip3 install -r requirements.txt

before_script:
  - cp .env.json.example .env.json
  - echo "{\"status\":\"done\",\"chunks\":{\"vendor\":[]}}" > /home/travis/build/savoirfairelinux/starlight/starlight/static/webpack-stats-vendor.json
  - echo "{\"status\":\"done\",\"chunks\":{\"app\":[]}}" > /home/travis/build/savoirfairelinux/starlight/starlight/static/webpack-stats-app.json

script:
  - tox -e $TOXENV

after_success:
  - coveralls
