version: '3.4'

services:
 db:
    image: postgres
 web:
    build: .
    command: >
         sh -c
          "python3 manage.py migrate
          python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
 livereload:
    build:
      context: ./
    command: sh -c "npm run webpack:vendor && npm run webpack:dev"
    volumes:
      - ./starlight/static:/code/starlight/static:rw
    ports:
      - "8081:8081"
